// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVPzY3v5JFhLvessoG_d0zTig8HQFKqcI',
    appId: '1:89659808714:android:0ec3bef0bf48adcf2b0d33',
    messagingSenderId: '89659808714',
    projectId: 'flutter-warp',
    storageBucket: 'flutter-warp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePwnxAx2VmkjGdbmMcuVqfAlrxUb0EXg',
    appId: '1:89659808714:ios:435314ff2e488c292b0d33',
    messagingSenderId: '89659808714',
    projectId: 'flutter-warp',
    storageBucket: 'flutter-warp.appspot.com',
    iosClientId: '89659808714-n8duhjbsrbhm1k0kcci9uc9usn715tei.apps.googleusercontent.com',
    iosBundleId: 'com.example.wave',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-B9ph1r0uDTugVc9E1dojToeqYs3XS8',
    appId: '1:89659808714:web:1b508bc67a9c8a9f2b0d33',
    messagingSenderId: '89659808714',
    projectId: 'flutter-warp',
    authDomain: 'flutter-warp.firebaseapp.com',
    storageBucket: 'flutter-warp.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCePwnxAx2VmkjGdbmMcuVqfAlrxUb0EXg',
    appId: '1:89659808714:ios:210ff44ba2f660c32b0d33',
    messagingSenderId: '89659808714',
    projectId: 'flutter-warp',
    storageBucket: 'flutter-warp.appspot.com',
    iosClientId: '89659808714-odcqaavhh9vgrq9kgl3lh5e0qbcug1cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myitsChirp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK-B9ph1r0uDTugVc9E1dojToeqYs3XS8',
    appId: '1:89659808714:web:40900363213941a22b0d33',
    messagingSenderId: '89659808714',
    projectId: 'flutter-warp',
    authDomain: 'flutter-warp.firebaseapp.com',
    storageBucket: 'flutter-warp.appspot.com',
  );

}